---
# tasks file for WebApp
- name: Install Nginx, yum-utils
  yum: name={{ item }} state=latest
  loop:
    - nginx
    - yum-utils
    - php-mbstring

- name: Site config
  copy: src=cms.zzz.chat.conf dest=/etc/nginx/conf.d/cms.zzz.chat

- name: Install remi repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: Enable PHP73 Repo
  command: yum-config-manager --enable remi-php73

- name: Install PHP stuff
  yum: name={{ item }} state=latest
  loop:
    - php-fpm
    - php-cli
    - php-gd
    - php-opcache
    - php-mysqlnd
    - php-json
    - php-mcrypt
    - php-xml
    - php-curl
    - php73-php-pgsql

- name: Cnfigure PDO
  copy: src=postgres.ini dest=/etc/php.d/postgres.ini

- name: Configure PHP-FPM
  shell: sed -i 's/user \= apache/user \= nginx/g' /etc/php-fpm.d/www.conf && 
           sed -i 's/group \= apache/group \= nginx/g' /etc/php-fpm.d/www.conf && 
           chown -R root:nginx /var/lib/php/*

- name: Download Drupal
  shell: wget -O /tmp/Joomla_3-9-16-Stable-Full_Package.tar.gz https://downloads.joomla.org/us/cms/joomla3/3-9-16/Joomla_3-9-16-Stable-Full_Package.tar.gz &&
         mkdir -p /var/www/cms.zzz.chat &&
         tar -xf /tmp/Joomla_3-9-16-Stable-Full_Package.tar.gz --directory /var/www/cms.zzz.chat &&
         chown -R nginx:nginx /var/www/cms.zzz.chat

- name: SUDO settings for /var/www
  shell: semanage fcontext -a -t httpd_sys_content_t /var/www\(/.*\)? && restorecon -Rv /var/www

- name: Start Nginx
  service: 
    name: nginx 
    enabled: yes
    state: restarted

- name: Start PHP-FPM
  service: 
    name: php-fpm 
    enabled: yes
    state: restarted

