---
# tasks file for balancer

- name: Install Nginx
  yum: name=nginx state=latest

- name: Nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644

- name: Copy default config
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Copy conifg file for CMS
  copy: src=cms.zzz.chat.conf dest=/etc/nginx/conf.d/cms.zzz.chat.conf

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted