---
# tasks file for router
- sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes


- name: Configure network interface eth0
  copy: src=ifcfg-eth0 dest=/etc/sysconfig/network-scripts/ifcfg-eth0
 
- name: Configure network IPV6FORWARDING
  copy: src=network dest=/etc/sysconfig/network

- name: Configure network interface eth1
  template: src=ifcfg-eth1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth1

- name: Configure network interface eth2
  template: src=ifcfg-eth2.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth2
  notify: Manage network


- name: Install Quagga
  yum: name=quagga state=latest

- name: Configure BGP for isp
  copy: src=bgpd.isp dest=/etc/quagga/bgpd.conf mode=0600 owner=quagga
  when: (ansible_facts['hostname'] == "isp")

- name: Configure BGP for routers
  template: src=bgpd.j2 dest=/etc/quagga/bgpd.conf mode=0600 owner=quagga
  when: (ansible_facts['hostname'] != "isp")

- name: Enable Zebra
  service:
    name: zebra
    enabled: yes
    state: started

- name: Enable BGPd
  service:
    name: bgpd
    enabled: yes
    state: started

- name: Install and configure VRRP
  block:
    - name: Install keepkeepalived
      yum: name=keepalived state=latest
    
    - name: Configure keepalived for routers
      template: src=keepalived.j2 dest=/etc/keepalived/keepalived.conf mode=0666 owner=root
    
    - name: Enable VRRP
      service:
        name: keepalived
        enabled: yes
        state: started
  
  when: (ansible_facts['hostname'] != "isp")
    
