---
# Copy backup of DBs

    - name: Copy database
      copy: src=cmsdb.gz dest=/tmp
      when: "{{ inventory_hostname == {{ master_name.stdout }} }}"

    - name: Copy database
      copy: src=zabbix.sql dest=/tmp
      when: "{{ inventory_hostname == {{ master_name.stdout }} }}"