---
# tasks file for Database

- name: Install Postgre REPO
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL
  yum: name={{ item }} state=latest
  loop:
    - postgresql96
    - postgresql96-server
    - postgresql96-contrib 
    - python-psycopg2    
    - python-ipaddress
  notify: InitDB

- name: InitDB
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb

- name: Grant local connect
  postgresql_pg_hba:
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    contype: local
    users: postgres
    databases: all
    method: trust

- name: Grant user from network 10.10.10.0/24
  postgresql_pg_hba:
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    contype: host
    users: all
    source: 10.10.10.0/24
    databases: all
    method: md5

- name: Grant user from network 127.0.0.1
  postgresql_pg_hba:
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    contype: host
    users: all
    source: 127.0.0.1/32
    databases: all
    method: trust

- name: Grant user from network ::1/128
  postgresql_pg_hba:
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    contype: host
    users: all
    source: ::1/128
    databases: all
    method: trust

- name: Listen all addresses
  lineinfile:
    path: /var/lib/pgsql/9.6/data/postgresql.conf
    regexp: '#listen_addresses ='
    line: listen_addresses = '*'

- name: Sudoers postgres
  lineinfile:
    path: /etc/sudoers
    line: postgres   ALL=(ALL)   NOPASSWD:ALL

- name: Start PostgreSQL Server
  service: 
    name: postgresql-9.6
    enabled: yes
    state: restarted

- name: Create a new database with name "cmsdb"  
  become: yes
  become_user: postgres
  postgresql_db:
    name: cmsdb
    state: present
    encoding: UTF-8

- name: Create DB User
  become: yes
  become_user: postgres
  postgresql_user:
    db: cmsdb
    name: cmska
    password: LoG0peD
    state: present
    priv: CONNECT
    login_user: postgres

- name: Copy database
  copy: src=cmsdb.gz dest=/tmp/cmsdb.gz

- name: Restore database "cmsdb"  
  become: yes
  become_user: postgres
  postgresql_db:
    name: cmsdb
    target: /tmp/cmsdb.gz
    state: restore

