---
# tasks file for init

- name: Disable yum fastestmirror plugin
  lineinfile:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: '^enabled=1'
    line: enabled=0
  
- name: Epel-release
  yum: name=epel-release state=latest

# - name: Update all packages
#   yum: name=* state=latest

- name: Install stuff
  yum: name={{ item }} state=latest
  loop:
    - nano
    - mc
    - htop
    - wget
    - curl
    - tree
    - unzip

- unarchive:
    src: mcfg.tar.gz
    dest: /root

- name: Install pip
  yum: name={{ item }} state=latest
  loop: 
    - python2-pip
    - python3-pip
    
- sysctl:
      name: vm.swappiness
      value: '10'
      sysctl_file: /etc/sysctl.d/10-vmswappines.conf
      state: present
      reload: yes

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive