---
# tasks file for ELK

    - name: Enable ELK repo
      copy: 
        src: elk.repo
        dest: /etc/yum.repos.d/elasticsearch.repo
    
    - shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Install ELK
      yum: name={{ item }} state=latest
      loop:
        - java-11-openjdk-devel
        - elasticsearch
        - kibana
        - borgbackup
        # - logstash
    
    - name: Copy Kibana config
      copy: src=kibana.yml dest=/etc/kibana/kibana.yml

    - name: Copy Elastic config
      copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
    
    # - name: Copy Logstash config
    #   copy: src=logstngx.conf dest=/etc/logstash/conf.d/logstngx.conf



    # - name: Start Logstash
    #   service: 
    #     name: logstash
    #     enabled: yes
    #     state: started