- hosts: db1
  become: yes
  vars:
    ipv4_eth1: '10.10.10.14'
    ipv6_eth1: '2600:70ff:b0ea:1::14'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
    - Patroni


- hosts: db2
  become: yes
  vars:
    ipv4_eth1: '10.10.10.15'
    ipv6_eth1: '2600:70ff:b0ea:1::15'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
    - Patroni

- hosts: db3
  become: yes
  vars:
    ipv4_eth1: '10.10.10.16'
    ipv6_eth1: '2600:70ff:b0ea:1::16'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    -  role: dj-wasabi.zabbix-agent
       zabbix_agent_server: 10.10.10.17
       zabbix_agent_serveractive: 10.10.10.17
       zabbix_create_host: present
       zabbix_agent_allowroot: 1
       zabbix_selinux: true
       zabbix_host_groups: 
                     - Linux Servers
       zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
    - Patroni
    - InstallDB   


- name: Install DBProxy
  include: dbproxy.yml 
