- hosts: dbproxy
  become: yes
  vars:
    ipv4_eth1: '10.10.10.13'
    
    ipv4_gw: '10.10.10.1'
    
  
  roles: 
    - NetConfig
    - Consul
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
    - Haproxy
    - InstallDB

