---

- hosts: all
  become: yes
  # roles:
  #   - init

- hosts: isp
  become: yes
  vars:
    ipv4_eth1: '10.0.1.201'
    ipv4_eth2: '10.10.1.1'
    ipv6_eth1: '2001:470:28:b72::cafe'
    ipv6_eth2: '2600:70ff:b0ea:cafe::1'
    ipv4_gw: '10.0.1.1'
    ipv6_gw: '2001:470:28:b72:52ff:20ff:fe27:4ff8'
  roles:
    - NetConfig
    
 