---

- hosts: all
  become: yes
  roles:
    - init

- name: Configure routers
  include: routers.yml

- name: Configure Backup Server
  include: bckp.yml 

- name: Configure Database
  include: db.yml

- name: Install DBProxy
  include: dbproxy.yml 

- name: Configure Zabbix-Server
  include: zabbix.yml 

- name: Configure web-servers
  include: web.yml

- name: Configure ELK
  include: elk.yml 