---

- hosts: all
  become: yes
  roles:
    - init

# - name: Configure routers
#   include: routers.yml

# - name: Configure web-servers
#   include: web.yml

# - name: Configure Database
#   include: db.yml

# - name: Configure Zabbix-Server
#   include: zabbix.yml 

- name: Configure ELK
  include: elk.yml 