---

- hosts: all
  become: yes
  roles:
      - init

- hosts: isp
  become: yes
  vars:
    ipv4_eth1: '10.0.1.201'
    ipv4_eth2: '10.10.1.1'
    ipv6_eth1: '2001:470:28:b72::cafe'
    ipv6_eth2: '2600:70ff:b0ea:cafe::1'
    ipv4_gw: '10.0.1.2'
    ipv6_gw: '2001:470:28:b72::1'
  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent

    
- hosts: router1
  become: yes
  vars:
    ipv4_eth1: '10.10.1.2'
    ipv4_eth2: '10.10.10.2'
    ipv6_eth1: '2600:70ff:b0ea:cafe::2'
    ipv6_eth2: '2600:70ff:b0ea:1::b00b'
    ipv4_gw: '10.10.1.1'
    ipv6_gw: '2600:70ff:b0ea:cafe::1'
    vrrp_state: 'MASTER'
    vrrp_prio: '101'

  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent


- hosts: router2
  become: yes
  vars:
    ipv4_eth1: '10.10.1.3'
    ipv4_eth2: '10.10.10.3'
    ipv6_eth1: '2600:70ff:b0ea:cafe::3'
    ipv6_eth2: '2600:70ff:b0ea:1::dead'
    ipv4_gw: '10.10.1.1'
    ipv6_gw: '2600:70ff:b0ea:cafe::1'
    vrrp_state: 'BACKUP'
    vrrp_prio: '100'
  
  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent

- hosts: balancer
  become: yes
  vars:
    ipv4_eth1: '10.10.10.10'
    ipv6_eth1: '2600:70ff:b0ea:1::10'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - balancer
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
                     - Template App Nginx by Zabbix agent
  
- hosts: webapp1
  become: yes
  vars:
    ipv4_eth1: '10.10.10.11'
    ipv6_eth1: '2600:70ff:b0ea:1::11'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles:
    - NetConfig
    - WebApp
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
                     - Template App Nginx by Zabbix agent

- hosts: webapp2
  become: yes
  vars:
    ipv4_eth1: '10.10.10.12'
    ipv6_eth1: '2600:70ff:b0ea:1::12'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - WebApp
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
                     - Template App Nginx by Zabbix agent
- hosts: webapp3
  become: yes
  vars:
    ipv4_eth1: '10.10.10.53'
    ipv6_eth1: '2600:70ff:b0ea:1::53'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - WebApp

- hosts: dbproxy
  become: yes
  vars:
    ipv4_eth1: '10.10.10.13'
    ipv6_eth1: '2600:70ff:b0ea:1::13'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    #- NetConfig
    - Dbproxy


- hosts: db1
  become: yes
  vars:
    ipv4_eth1: '10.10.10.14'
    ipv6_eth1: '2600:70ff:b0ea:1::14'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    #- NetConfig
    #- Database
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
                     - Template DB PostgreSQL

- hosts: db2
  become: yes
  vars:
    ipv4_eth1: '10.10.10.15'
    ipv6_eth1: '2600:70ff:b0ea:1::15'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - Database

- hosts: db3
  become: yes
  vars:
    ipv4_eth1: '10.10.10.16'
    ipv6_eth1: '2600:70ff:b0ea:1::16'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    - NetConfig
    - Database

- hosts: zabbix
  become: yes
  vars:
    ipv4_eth1: '10.10.10.17'
    ipv6_eth1: '2600:70ff:b0ea:1::17'
    ipv4_gw: '10.10.10.1'
    ipv6_gw: '2600:70ff:b0ea:1::b0b'
  
  roles: 
    #- NetConfig
    - { role: dj-wasabi.zabbix-server, 
              zabbix_server_name: zabbix,
              zabbix_selinux: true,
              zabbix_server_database: pgsql,
              zabbix_server_database_long: postgresql,
              zabbix_server_dbhost: 10.10.10.14,
              zabbix_server_dbname: zabbix,
              zabbix_server_dbuser: zabbix,
              zabbix_server_dbpassword: LoG0peD,
              zabbix_database_creation: false }
    - { role: dj-wasabi.zabbix-web,                
              zabbix_server_database: pgsql,
              zabbix_server_database_long: postgresql,
              zabbix_server_dbhost: 10.10.10.14,
              zabbix_server_dbname: zabbix,
              zabbix_server_dbuser: zabbix,
              zabbix_server_dbpassword: LoG0peD,
              zabbix_timezone: Europe/Moscow,
              zabbix_vhost: false }
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
                     - Template App Apache by Zabbix agent
                     - Template App Zabbix Server
