- hosts: isp
  become: yes
  vars:
    ipv4_eth1: '10.0.1.201'
    ipv4_eth2: '10.10.1.1'
    ipv6_eth1: '2001:470:28:b72::cafe'
    ipv6_eth2: '2600:70ff:b0ea:cafe::1'
    ipv4_gw: '10.0.1.2'
    ipv6_gw: '2001:470:28:b72::1'
  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent

    
- hosts: router1
  become: yes
  vars:
    ipv4_eth1: '10.10.1.2'
    ipv4_eth2: '10.10.10.2'
    ipv6_eth1: '2600:70ff:b0ea:cafe::2'
    ipv6_eth2: '2600:70ff:b0ea:1::b00b'
    ipv4_gw: '10.10.1.1'
    ipv6_gw: '2600:70ff:b0ea:cafe::1'
    vrrp_state: 'MASTER'
    vrrp_prio: '101'

  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent


- hosts: router2
  become: yes
  vars:
    ipv4_eth1: '10.10.1.3'
    ipv4_eth2: '10.10.10.3'
    ipv6_eth1: '2600:70ff:b0ea:cafe::3'
    ipv6_eth2: '2600:70ff:b0ea:1::dead'
    ipv4_gw: '10.10.1.1'
    ipv6_gw: '2600:70ff:b0ea:cafe::1'
    vrrp_state: 'BACKUP'
    vrrp_prio: '100'
  
  roles:
    - NetConfig
    - router
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 10.10.10.17
      zabbix_agent_serveractive: 10.10.10.17
      zabbix_create_host: present
      zabbix_agent_allowroot: 1
      zabbix_selinux: true
      zabbix_host_groups: 
                     - Linux Servers
      zabbix_link_templates:
                     - Template OS Linux by Zabbix agent
